version:  '3.9'
services:
  customer-service:
    image: mysql:latest
    container_name: customer-service
    networks:
      - customer-network
    ports:
      - 3306:3306


    environment:
      MYSQL_ROOT_PASSWORD:  root
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: root
      MYSQL_ALLOW_EMPTY_PASSWORD: "yes"

  customer-authentication-service:
    image:  customer-auth
    container_name: customer-authentication-service
    build:  ./
    networks:
      - customer-network
    ports:
      - 8084:8084
    depends_on:
      - customer-service
networks:
  customer-network:
    driver: bridge




